### ISSUE TITLE
Go to next/previous sibling not working

### ISSUE THREAD

**Issue by maubuz** [vipzhicheng/logseq-plugin-vim-shortcuts#56]
Go to next and previous sibling (`shift + j` / `shift + k`) is no longer working in logseq `0.10.6` via snap on Ubuntu 23.10, vim-shortcuts `v0.1.22`.

I've recently migrated my system from Fedora to Ubuntu and just noticed these shortcuts no longer work. Other shortcuts seem to work fine. I loaded logseq with the Dev Tools console and I see messages about the shortcuts being registered. For example:
```
:shortcut/register-shortcut [:shortcut.handler/global-non-editing-only :plugin.logseq-vim-shortcuts/vim-shortcut-next-sibling-0 {:fn #object[Function], :desc nil, :key vim-shortcut-next-sibling-0, :type $palette$, :binding (shift+j), :label Go to next sibling, :cmd {:id :plugin.logseq-vim-shortcuts/vim-shortcut-next-sibling-0, :desc Go to next sibling, :shortcut shift+j, :handler-id :shortcut.handler/global-non-editing-only, :action #object[Function]}, :keybinding {:mode non-editing, :binding shift+j}, :extras nil}]
```
However, when I try to use the shortcut (eg. `shift + j`), I get the following error:

```
index.e8f2ed0c.js:1018 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'uuid')
    at g6 (index.e8f2ed0c.js:1018:19313)
    at async qr.<anonymous> (index.e8f2ed0c.js:1018:19793)
```

I'm happy to help debug. I noticed that @Weiming-Hu recently commented on #41 about this issue. Maybe related?
Thank you so much for this amazing extension!

**Comment by Weiming-Hu** [comment]
Thanks for reporting. Can you show me where to find the error message? I want to confirm whether we had the same errors.

**Comment by maubuz** [comment]
I first activated _Developer Mode_ in logseq settings and then opened the _Developer Tools_ with `ctrl + shit +i`. Once in _Developer Tools_, I opened the _Console_ tab to see if anything was being logged by the plugin. I also disabled all other plugins to avoid extra logs.
This process is well described in this [logseq forum discussion](https://discuss.logseq.com/t/how-to-enable-the-inspector-developer-tools/9428) and in the [Chrome Dev Tools documentation](https://developer.chrome.com/docs/devtools/console). Hope this helps.

**Comment by Weiming-Hu** [comment]
Thank you for the instructions. I was able to capture the error message. It looks like we are hitting the same error. Details below.

```
index.e8f2ed0c.js:1018 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'uuid')
    at F6 (index.e8f2ed0c.js:1018:22219)
    at async qr.<anonymous> (index.e8f2ed0c.js:1018:22674)
```

**Comment by maubuz** [comment]
It looks like this issue was introduced in version `0.1.21` of this plugin with commit [707eca6](https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/commit/707eca6f0935cf3bb148c15d6a555c73081c0f8f). I was able to install version `0.1.20` of the plugin and `shift+j` and `shift+k` work as expected.

To install previous versions of this plugin I used the logseq feature _Install plugins from plugins.edn_, which is [described in the docs](https://docs.logseq.com/#/page/plugins.edn).
Content of my `.logseq/config/plugins.edn` file:
```clojure
{
:logseq-plugin-vim-shortcuts {:version "v0.1.20", :repo "vipzhicheng/logseq-plugin-vim-shortcuts", :effect true, :theme false}
}
```

**Comment by Weiming-Hu** [comment]
Confirm that `0.1.20` works for me. But always happy to test further if needed.
